import "./globals.css";
import localFont from "next/font/local";

const neueBold = localFont({
  src: "../public/assets/fonts/NeueHaasDisplayBold.ttf",
  weight: "800",
});
const neueNormal = localFont({
  src: "../public/assets/fonts/NeueHaasDisplayRoman.ttf",
  weight: "400",
});

export const metadata = {
  title: "FORCE ACADEMY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${neueNormal.className} ${neueBold.className} bg-black`}
      >
        {children}
      </body>
    </html>
  );
}
